import type { Metadata } from "next";
import { Geist, Geist_Mono, Belleza } from "next/font/google";

import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { AuthProvider } from "./contexts/AuthContext";
import { CartProvider } from "./contexts/Cartcontext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const belleza = Belleza({
  variable: "--font-belleza",
  subsets: ["latin"],
  weight: ["400"]
})

export const metadata: Metadata = {
  title: "Vivero Agronomía",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` text- foreground bg-background ${belleza.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <CartProvider>
          <> 
        <Navbar/>
        {children}
        <Footer/>
          </>
        </CartProvider>
        </AuthProvider>
       
      </body>
    </html>
  );
}
